[package]
name = "rsBPF"
version = "0.1.0"
authors = ["Xingfeng Yang <xingfeng.yang@thoughtworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
